name = "monarch-doctor-run"
main = "src/index.js"
compatibility_date = "2026-04-26"

workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "monarch_doctor_runs"
database_id = "1bcbd55b-10b6-41e7-a9a1-bd0ab980aec0"
